scrape_configs:
  - job_name: gateway
    scrape_interval: 5s
    static_configs:
      - targets:
          - gateway:3000
    authorization:
      type: Bearer
      credentials: AUTH

  - job_name: api
    scrape_interval: 5s
    static_configs:
      - targets:
          - api:3000
    authorization:
      type: Bearer
      credentials: AUTH

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
          - cadvisor:8080
